### ISSUE TITLE
`tau` function is missing but needed

### ISSUE THREAD

**Issue by yegor256** [objectionary/phino#149]
This is my expression:

```
{⟦ m ↦ "foo", foo ↦ ⟦⟧ ⟧}
```

This is what I want to do:

```
name: foo
pattern: '⟦ 𝜏1 ↦ 𝑒1, 𝜏2 ↦ 𝑒2 ⟧'
result: '⟦ 𝜏1 ↦ 𝑒2 ⟧'
when:
  eq:
    - 𝜏3
    - 𝜏2
where:
  - meta: 𝜏3
    function: tau
    args:
      - 𝑒1
```

In order to get this:

```
{⟦ m ↦ ⟦⟧ ⟧}
```

The `tau` is currently missing, but needed. It should take the expression, dataize it to bytes, and then convert bytes to tau (if possible). If not possible (due to syntax error), raise exception.
