### ISSUE TITLE
transitive encapsulation operator is not implemented

### ISSUE THREAD

**Issue by yegor256** [objectionary/phino#150]
This is my expression:

```
{⟦ foo ↦ ⟦ t ↦ ⟦ k ↦ ⟦ bar ↦ ∅ ⟧ ⟧ ⟧ ⟧}
```

This is what I want to do:

```yaml
name: foo
pattern: '⟦ 𝜏 ↝ ∅ ⟧'    # pay attention, a new arrow symbol here!
result: '⟦ 𝜏 ↦ ⟦⟧ ⟧'
```

In order to get this:

```
{⟦ foo ↦ ⟦⟧ ⟧}
```

We introduced this "transitive encapsulation" operator in [this paper](https://dl.acm.org/doi/pdf/10.1145/3638584.3638679). Simply put, `𝜏 ↝ ∅` means that `𝜏` is bound to `∅` _through_ a number of formations.
