### ISSUE TITLE
The `concat` function is not implemented but needed

### ISSUE THREAD

**Issue by yegor256** [objectionary/phino#151]
When #149 is implemented, we need this.

This is my expression:

```
{⟦ m ↦ "foo", foobar ↦ ⟦⟧ ⟧}
```

This is what I want to do:

```
name: simple
pattern: '⟦ 𝜏1 ↦ 𝑒1, 𝜏2 ↦ 𝑒2 ⟧'
result: '⟦ 𝜏1 ↦ 𝑒2 ⟧'
when:
  eq:
    - 𝜏3
    - 𝜏2
where:
  - meta: 𝑒3
    function: concat
    args:
      - 𝑒1
      - "bar"
  - meta: 𝜏3
    function: tau
    args:
      - 𝑒3
```

In order to get this:

```
{⟦ m ↦ ⟦⟧ ⟧}
```

The `concat` is currently missing, but needed. It should take two expressions as arguments, dataize them both to bytes, and then concatenate.
