### ISSUE TITLE
`sed` function is missing but needed

### ISSUE THREAD

**Issue by yegor256** [objectionary/phino#152]
When #149 is implemented, we need this.

This is my expression:

```
{⟦ m ↦ "  foo bar  ", foobar ↦ ⟦ ⟧ ⟧}
```

This is what I want to do:

```
name: simple
pattern: '⟦ 𝜏1 ↦ 𝑒1, 𝜏2 ↦ 𝑒2 ⟧'
result: '⟦ 𝜏1 ↦ 𝑒2 ⟧'
when:
  eq:
    - 𝜏3
    - 𝜏2
where:
  - meta: 𝑒3
    function: sed
    args:
      - 𝑒1
      - "/\s+//g"
  - meta: 𝜏3
    function: tau
    args:
      - 𝑒3
```

In order to get this:

```
{⟦ m ↦ ⟦⟧ ⟧}
```

The `sed` is currently missing, but needed. It should take two expressions as arguments, dataize them both to bytes, and then apply the second one to the first one as a regular expression substitution (similar to the [`sed` command](https://www.gnu.org/software/sed/manual/sed.html)).
