### ISSUE TITLE
locators are not supported by needed

### ISSUE THREAD

**Issue by yegor256** [objectionary/phino#153]
Once #150 is implemented, we need this.

This is my expression:

```
{⟦ foo ↦ ⟦ bar ↦ ⟦ t ↦ ⟦⟧ ⟧ ⟧, m ↦ ∅ ⟧}
```

This is what I want to do:

```yaml
name: foo
pattern: '⟦ 𝜅 ↝ 𝑒, 𝜏 ↦ ∅ ⟧'  # transitive encapsulation here!
result: '⟦ 𝜏 ↦ 𝑒 ⟧'
where:
  - meta: 𝜅
    function: locator
    args:
      - "foo.bar.t"
```

In order to get this:

```
{⟦ m ↦ ⟦⟧ ⟧}
```

The `locator` is currently missing, but needed. It should take the expression, dataize it to bytes, and then convert bytes to kappa (if possible). If not possible (due to syntax error), raise exception.
