### ISSUE TITLE
Condition to Verify Attribute Presence in Meta Bindings Not Implemented

### ISSUE THREAD

**Issue by maxonfjvipon** [objectionary/phino#33]
For this normalization rule:

<img width="583" alt="Image" src="https://github.com/user-attachments/assets/8e17df7c-5071-408e-8ccb-9c7cbb120296" />

We should implement the condition that would allow to check if given attribute (or meta attribute) exists in given meta binding.

In yaml rule set it may look like:

```yaml
title: ruleset
rules:
  - name: phi
    pattern: |
      [!B].!a
    result: |
      [!B].@.!a
    when:
      and:
        belongs-to:
          attrs: [!a]
          bindings: [!B]
```

**Comment by maxonfjvipon** [comment]
@yegor256 WDYT?

**Comment by yegor256** [comment]
@maxonfjvipon maybe just like this:

```
when:
  and:
    - in:
      - !a
      - !B
```

This means (Lisp-like prefix notation): `(and (in !a !B))`

Every function (such as `and` and `in`) have parameters, which are either scalars or functions. 

If they are **scalars**, they are provided as unnamed array items:

```
- !a
- !B
```

If they are **functions**, they have also array items, but with names:

```
- in:
```
