### ISSUE TITLE
Inability to Split Large YAML Rule Set into Individual Rule Files

### ISSUE THREAD

**Issue by maxonfjvipon** [objectionary/phino#36]
Right now we assume that we have one yaml file with all necessary rules:
```yaml
title: rule set
rules:
  - name: rule1
    pattern: ...
    result: ...
  - name: rule2
    pattern: ...
    result: ...
```

It's not convenient for testing because to test each rule we should copy the part from this rules and past it into test pack:
```yaml
ruleSet:
  title: test rule1
  rules:
    - name: rule1
      pattern: ...
      result: ...
input: ...
output: ...
```

I think it would be more convenient if we have small yaml file for each rule:
```yaml
# rule1.yaml
name: rule1
pattern: ...
result: ...

# rule2.yaml
name: rule2
pattern: ...
result: ...
```

In such case it would be easy to test them:
```
# simple-test-rule1.yaml
rule: rule1
input: ...
output: ...

# complex-test-rule1.yaml
rule: rule1
input: ...
output: ...
```

But such concept has one limitation. It's not clear how to pass such small rules into CLI. Right now it accepts `--phi-input=my-rules.yaml` where `my-rules.yaml` is yaml rule set files with many rules.
