### ISSUE TITLE
Absence of `not` Rule in YAML Logic Negatively Impacts Functionality

### ISSUE THREAD

**Issue by maxonfjvipon** [objectionary/phino#43]
[Here](https://github.com/objectionary/phino/pull/42) we introduced basic yaml rules like `and`, `or` and `in`. It seems we also need the rule `not` which would accept only one nested rule and behaves like logical `not`:
```yaml
pattern: ...
result: ...
when:
  and:
    - in:
        - ['x']
        - ['!B']
    - not:
         in:
           - ['y']
           - ['!B']
```
