### ISSUE TITLE
`alpha` Function Not Implemented Prevents `Rmiss` Implementation

### ISSUE THREAD

**Issue by yegor256** [objectionary/phino#55]
We need to have `alpha` function implemented in order to enable the implementation of `Rmiss`:

```
---
name: MISS
pattern: '⟦!B⟧(!a ↦ !e)'
result: ⊥
where:
  and:
    - not: 
      - in:
        - [!a]
        - [!B]
    - not:
      - alpha: !a
```
